name: prune
description: Prune CloudFlare pages deployments

inputs:
  token:
    description: 'CloudFlare API token'
    required: true
  account_id:
    description: 'CloudFlare account ID'
    required: true
  project_name:
    description: 'Project name'
    required: true
  environment:
    description: 'Project name'
    required: false
    default: 'preview'
  keep:
    description: 'Number of deployments to keep'
    required: false
    default: '3'

runs:
  using: docker
  image: Dockerfile
  env:
    CLOUDFLARE_API_TOKEN: ${{ inputs.token }}
  args:
    - '--account=${{ inputs.account_id }}'
    - '--project=${{ inputs.project_name }}'
    - '--environment=${{ inputs.environment }}'
    - '--keep=${{ inputs.keep }}'
