name: CloudFlare Prune Pages
description: This action will prune old CloudFlare Pages deployment.
branding:
  icon: cloud-off
  color: orange

inputs:
  apiToken:
    description: 'CloudFlare API token'
    required: true
  accountId:
    description: 'CloudFlare account ID'
    required: true
  projectName:
    description: 'Project name'
    required: true
  environment:
    description: 'Project name'
    required: false
    default: 'preview'
  keep:
    description: 'Number of deployments to keep'
    required: false
    default: '3'

runs:
  using: docker
  image: Dockerfile
  env:
    CLOUDFLARE_API_TOKEN: ${{ inputs.apiToken }}
  args:
    - '--accountId=${{ inputs.accountId }}'
    - '--projectName=${{ inputs.projectName }}'
    - '--environment=${{ inputs.environment }}'
    - '--keep=${{ inputs.keep }}'
