name: prune
description: Prune CloudFlare pages deployments

inputs:
  token:
    description: 'CloudFlare API token'
    required: true
  account_id:
    description: 'CloudFlare account ID'
    required: true
  project_name:
    description: 'Project name'
    required: true
  keep:
    description: 'Number of deployments to keep'
    required: false
    default: '3'

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v5

    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install cloudflare

    - name: prune
      shell: bash
      run: python main.py --account=${{ inputs.account_id }} --project=${{ inputs.project_name }} --keep=${{ inputs.keep }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.token }}